In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [4]:
df = pd.read_csv('/content/cleaned_data.csv')

In [5]:
df

       Unnamed: 0     price  bedrooms  bathrooms  sqft_living  grade
0               0  221900.0       3.0        2.0     0.067170      7
1               1  538000.0       3.0        2.0     0.172075      7
2               2  180000.0       2.0        1.0     0.036226      6
3               3  604000.0       4.0        3.0     0.126038      7
4               4  510000.0       3.0        2.0     0.104906      8
...           ...       ...       ...        ...          ...    ...
21604       21608  360000.0       3.0        3.0     0.093585      8
21605       21609  400000.0       4.0        3.0     0.152453      8
21606       21610  402101.0       2.0        1.0     0.055094      7
21607       21611  400000.0       3.0        3.0     0.098868      8
21608       21612  325000.0       2.0        1.0     0.055094      7

[21609 rows x 6 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21609 entries, 0 to 21608
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   21609 non-null  int64
 1   price        21609 non-null  float64
 2   bedrooms     21609 non-null  float64
 3   bathrooms    21609 non-null  float64
 4   sqft_living  21609 non-null  float64
 5   grade        21609 non-null  int64
dtypes: float64(4), int64(2)
memory usage: 1013.1 KB

In [7]:
df = df.drop('Unnamed: 0', axis=1)

In [8]:
df

          price  bedrooms  bathrooms  sqft_living  grade
0      221900.0       3.0        2.0     0.067170      7
1      538000.0       3.0        2.0     0.172075      7
2      180000.0       2.0        1.0     0.036226      6
3      604000.0       4.0        3.0     0.126038      7
4      510000.0       3.0        2.0     0.104906      8
...         ...       ...        ...          ...    ...
21604  360000.0       3.0        3.0     0.093585      8
21605  400000.0       4.0        3.0     0.152453      8
21606  402101.0       2.0        1.0     0.055094      7
21607  400000.0       3.0        3.0     0.098868      8
21608  325000.0       2.0        1.0     0.055094      7

[21609 rows x 5 columns]

In [9]:
X = df.drop('price', axis=1)
y = df['price']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

In [11]:
ln = LinearRegression()

In [12]:
ln.fit(X_train, y_train)

LinearRegression()

In [13]:
y_pred = ln.predict(X_test)

In [14]:
y_pred[0:4]

array([ 404175.69845492, 1139371.50020245,  561648.70766426,
        320438.10566505])

In [15]:
y_test[0:4]

6525     330000.0
9103     925000.0
3057     790000.0
14431    475000.0
Name: price, dtype: float64

In [16]:
from sklearn.metrics import r2_score

accuracy = r2_score(y_test, y_pred)
print(f"Model Accuracy (R-squared): {accuracy:.2f}")

Model Accuracy (R-squared): 0.57